### ISSUE TITLE
Compatibility with Long Reads (Nanopore)?

### ISSUE THREAD

**Issue by m-ocejo** [Isabella136/AmrPlusPlus_SNP#31]
Hello,
Thanks for developing this tool! I'm looking to run it with nanopore long reads. Have you tried using it for that before?  Could you share any experiences or insights regarding its application for this type of data? I'd love to know how well it works and whether the results are reliable.

Thanks for any tips or insights you can share!

Best,

Medelin

**Comment by Isabella136** [comment]
This tool was specifically made to work with AMR++ which overall performs resistome analysis through short read alignment. Now, if you're only interested in using this tool for the identification of resistance-conferring variants, it should work from a computational perspective. However, since this tool assumes that you are inputting pre-processed short read data, you'll have to take special care in interpreting the output correctly within the context of long-read data, which tends to have lower accuracy, especially at the base level

**Comment by m-ocejo** [comment]
Dear Isabella, thank you for your reply. Yes, we are interested in using the tool with AMR++.
For now, we are going to apply this for short-read datasets then.

Best regards!
